- name: "Installing httpd HTTP Server"
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
  
- name: "Installing apache2 HTTP Server"
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
